env:
  es6: true
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
    # 'import/prefer-default-export': off
    '@typescript-eslint/explicit-function-return-type': off,
    '@typescript-eslint/no-var-requires': warn,
    'eslint-disable-next-line functional/prefer-readonly-type': off,
    '@typescript-eslint/no-explicit-any': off,
    '@typescript-eslint/no-non-null-assertion': off,
  }
settings:
  import/resolver:
    node:
      extensions: ['.ts']
